### ISSUE TITLE
complement of a complement of an owl class should be equal to the owl class

### ISSUE THREAD

**Issue by Demirrr** [dice-group/owlapy#101]
```
A=OWLClass("http://example.com/father#A")
assert A.get_object_complement_of().get_object_complement_of() == A
```

**Comment by LckyLke** [comment]
Changing this:
https://github.com/dice-group/owlapy/blob/a82f76f52a76b6c100fa4e6c39a90d3a93761451/owlapy/class_expression/class_expression.py#L64-L66

To check if the provide class is already a complement:
```py
    def get_object_complement_of(self) -> 'OWLObjectComplementOf':
        # documented in parent
        if isinstance(self, OWLObjectComplementOf):
            return self.get_operand()
        return OWLObjectComplementOf(self)
```

**Comment by LckyLke** [comment]
or for more general solution, we could check this in the init of OWLObejctComplementOf?
Depends on if this automatic simplification is desired, I guess...

**Comment by Demirrr** [comment]
I like your proposed solution. What do you think @alkidbaci ?

**Comment by alkidbaci** [comment]
This is a great solution
