### ISSUE TITLE
Timeout for Reasoners

### ISSUE THREAD

**Issue by Demirrr** [dice-group/owlapy#69]
Can we introduce a timeout parameter for the reasoners? Ideally, we should ensure that the instance retrieval should not take more than the timeout

**Comment by alkidbaci** [comment]
So it should either return the instances before the timeout or return a error message that the timeout is exceeded? 
Should this parameter be relevant only for the `instances` method or for every method of the reasoner that retrieves something?

**Comment by Demirrr** [comment]
I guess It should return an empty set
