### ISSUE TITLE
Using Sync as a prefix

### ISSUE THREAD

**Issue by Demirrr** [dice-group/owlapy#79]
What is the purpose of using Sync as a prefix for few classes ?

**Comment by alkidbaci** [comment]
Those classes are using _owlapi_ for their functionalities and the idea of "Sync" is that those are synchronizing classes in a sense that nothing is actually implemented in our package and when you are calling a method in python, the actual processing is happening in some java library. Basically its "syncing" our framework with another framework. This naming is not my original idea and is based on a previous naming in owlapy which I believe is based on the naming in owlready2 for a similar functionality.

**Comment by Demirrr** [comment]
Yes I thought so. I guess we can start thinking about omitting this prefixing. 


I guess we need some refactroing in the [owl_reasoner.py](https://github.com/dice-group/owlapy/blob/develop/owlapy/owl_reasoner.py)

1. Move AbstractOWLReasonerEx into AbstractOWLReasoner (unclear why these inconvenience needed to be seperated) and
2. Implement OWLReasoner class

A reasoner should be created as
`reasoner= OWLReasoner(reasoner="Hermit | Pellet .... | FastInstanceCheckerReasoner")`

We might even need to rename `FastInstanceCheckerReasoner`

Does user need to know this concept of syncing?

**Comment by Demirrr** [comment]
Thank you for your explanations :)

I do agree with the aim of encouraging developers implement new reasoners that inherits from `AbstractOWLReasoner`.

In the following parts, I tried to adress few things.

> For example FastInstanceCheckerReasoner and SyncReasoner are very different ones, because the former operates under CWA (or partial CWA, still not clear where it stands) and the latter under OWA.

The used underlying assumption behind a reasoner (whether CWA or OWA) does not differ the funtionality/interface of a reasoner but **only the generated results**, e.g. `reasoner.instances(..)` or `reasoner.subclass(..)`

> We also have other reasoners in ontolearn like TripleStoreReasoner or Luke's neural reasoner.

Any other reasoners should also implement abstract methods---`instances()`, `subclass()` etc.

>  I understand that we can still have this distinction if we implement the suggested OWLReasoner class but we cannot put in the same choice list 'HermiT'/'Pellet'/... and FastInstanceCheckerReasoner. There is also the difference in libraries used to implement those reasoners. Therefore, i think its better to leave the structure as is.

Does the argument for not putting the HermiT'/'Pellet'/... and FastInstanceCheckerReasoner into the same choice list stem from the OWA and CWA distrinction or there is something else?


> Another thing you point out is naming. The reasoner-related classes has gone through some heavy renaming over the past few months and i feel like they are losing their significance.

I am not quite sure what does losing their significance mean ?


Let's move the discussion into a call :)

**Comment by alkidbaci** [comment]
All tasks that emerged during this issue are completed. 

For the record: During the call it was decided that renaming of "Sync" classes will not happen for the moment, hence considering this issue closed. A new issue can be opened if there is a change of decision.
