### ISSUE TITLE
Minor mistakes / inconsistencies in docs 

### ISSUE THREAD

**Issue by LckyLke** [dice-group/owlapy#87]
As default value for pop() is -1, which will give last item, i.e. "Stefan", and not "Anna":

![grafik](https://github.com/user-attachments/assets/9f4aa44a-be6d-4129-8a80-b5641ede782d)

17 instead of 18:
![grafik](https://github.com/user-attachments/assets/c3e64e16-acbd-4ff3-bb9d-0f7599f53dd6)

IRI import is missing:
![grafik](https://github.com/user-attachments/assets/f61c5659-af34-4b71-a095-5d034cb0dc01)

**Comment by Demirrr** [comment]
Thank you. All look good!
